# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = echo "lock"
}

listener {
    timeout = 25
    on-timeout = kitty --class FastfetchSaver --title Fastfetch bash -c "while true; do clear; fastfetch; sleep 3; done"
    on-resume = pkill -f 'kitty --class FastfetchSaver'
}
